# Generated by Django 3.0.7 on 2020-06-18 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=125)),
                ('movie_release', models.DateField()),
                ('movie_director', models.CharField(max_length=70)),
                ('movie_length', models.CharField(max_length=12)),
                ('movie_rating', models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R')], default='PG', max_length=5)),
                ('movie_summary', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'movies',
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=125)),
                ('review_date', models.DateField()),
                ('review_rating', models.CharField(choices=[('A', 'Exceptional'), ('B', 'Entertaining'), ('C', 'Amusing'), ('D', 'Tolerable'), ('E', 'Regrettable')], default='B', max_length=15)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmsnob.Movies')),
            ],
            options={
                'verbose_name_plural': 'reveiws',
                'db_table': 'review',
            },
        ),
    ]
