# Generated by Django 3.0.7 on 2020-06-18 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmsnob', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='movie_name',
            new_name='movie_title',
        ),
    ]
