# Generated by Django 3.0.7 on 2020-06-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmsnob', '0002_auto_20200618_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_text',
            field=models.TextField(blank=True),
        ),
    ]
