# Generated by Django 3.0.7 on 2020-06-19 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmsnob', '0003_review_review_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'reviews'},
        ),
    ]
